// client/src/app/components/engagement-heatmap/engagement-heatmap.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-engagement-heatmap',
  template: `
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Peak Engagement Heatmap</h3>
      </div>
      <div class="card-content">
        <div class="tabs-container">
          <div class="tab-list">
            <button 
              class="tab-trigger" 
              [class.active]="activeTab === 'engagement'"
              (click)="activeTab = 'engagement'">
              Engagement
            </button>
            <button 
              class="tab-trigger" 
              [class.active]="activeTab === 'conversion'"
              (click)="activeTab = 'conversion'">
              Conversion
            </button>
            <button 
              class="tab-trigger" 
              [class.active]="activeTab === 'cost'"
              (click)="activeTab = 'cost'">
              Cost Efficiency
            </button>
          </div>
          
          <div class="tab-content" *ngIf="activeTab === 'engagement'">
            <!-- Top Performing Channels -->
            <div class="channel-grid">
              <div *ngFor="let channel of channelPerformance" class="channel-card" [ngClass]="channel.bgColor">
                <h4>{{channel.name}}</h4>
                <p class="engagement-rate" [ngClass]="channel.textColor">{{channel.engagement}}</p>
                <p class="peak-time" [ngClass]="channel.textColor">Peak: {{channel.peak}}</p>
              </div>
            </div>

            <!-- Heatmap Grid -->
            <div class="heatmap-section">
              <h4>Engagement Heatmap by Time</h4>
              <div class="heatmap-table">
                <table>
                  <thead>
                    <tr>
                      <th></th>
                      <th>12 AM</th>
                      <th>6 AM</th>
                      <th>12 PM</th>
                      <th>6 PM</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr *ngFor="let row of heatmapData">
                      <td class="day-label">{{row.day}}</td>
                      <td *ngFor="let value of row.values; let i = index" class="heatmap-cell">
                        <div 
                          class="heatmap-square" 
                          [ngClass]="getHeatmapColor(value)"
                          [class.text-white]="getTextColor(value)">
                          {{row.percentages[i]}}
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Engagement Insights -->
            <div class="insights-section">
              <div class="insight-card">
                <div class="insight-icon">💡</div>
                <div class="insight-content">
                  <h5>Peak Performance</h5>
                  <p>Tuesday 10-11 AM shows highest engagement across channels</p>
                </div>
              </div>
              <div class="insight-card">
                <div class="insight-icon">📈</div>
                <div class="insight-content">
                  <h5>Optimization Opportunity</h5>
                  <p>Friday evening campaigns underperforming by 23%</p>
                </div>
              </div>
              <div class="insight-card">
                <div class="insight-icon">🎯</div>
                <div class="insight-content">
                  <h5>Weekend Pattern</h5>
                  <p>Weekend engagement drops 15% - consider adjusted timing</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
      margin-bottom: 20px;
    }
    
    .card-header {
      padding: 20px 20px 0;
      border-bottom: 1px solid #e2e8f0;
    }
    
    .card-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: #2d3748;
      margin: 0 0 16px 0;
    }
    
    .card-content {
      padding: 20px;
    }
    
    .tab-list {
      display: flex;
      border-bottom: 1px solid #e2e8f0;
      margin-bottom: 20px;
    }
    
    .tab-trigger {
      padding: 8px 16px;
      border: none;
      background: none;
      color: #718096;
      cursor: pointer;
      border-bottom: 2px solid transparent;
      transition: all 0.2s;
    }
    
    .tab-trigger.active {
      color: #667eea;
      border-bottom-color: #667eea;
    }
    
    .channel-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      margin-bottom: 24px;
    }
    
    .channel-card {
      padding: 16px;
      border-radius: 8px;
      border: 1px solid;
    }
    
    .channel-card.bg-green-50 {
      background-color: #f0fff4;
      border-color: #c6f6d5;
    }
    
    .channel-card.bg-blue-50 {
      background-color: #ebf8ff;
      border-color: #bee3f8;
    }
    
    .channel-card h4 {
      margin: 0 0 8px 0;
      font-weight: 600;
      color: #2d3748;
    }
    
    .engagement-rate {
      font-size: 1.5rem;
      font-weight: 700;
      margin: 0 0 4px 0;
    }
    
    .engagement-rate.text-green-700 {
      color: #2f855a;
    }
    
    .engagement-rate.text-blue-700 {
      color: #2b6cb0;
    }
    
    .peak-time {
      font-size: 0.875rem;
      margin: 0;
    }
    
    .peak-time.text-green-700 {
      color: #2f855a;
    }
    
    .peak-time.text-blue-700 {
      color: #2b6cb0;
    }
    
    .heatmap-section h4 {
      font-size: 0.875rem;
      font-weight: 600;
      color: #2d3748;
      margin-bottom: 12px;
    }
    
    .heatmap-table table {
      width: 100%;
      border-collapse: collapse;
    }
    
    .heatmap-table th,
    .heatmap-table td {
      text-align: center;
      padding: 8px 4px;
    }
    
    .day-label {
      color: #718096;
      text-align: left !important;
      padding-right: 16px !important;
    }
    
    .heatmap-cell {
      padding: 8px 2px;
    }
    
    .heatmap-square {
      width: 32px;
      height: 24px;
      border-radius: 4px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 600;
      margin: 0 auto;
    }
    
    .heatmap-square.bg-orange-100 {
      background-color: #fed7aa;
      color: #7c2d12;
    }
    
    .heatmap-square.bg-orange-200 {
      background-color: #fbbf24;
      color: #7c2d12;
    }
    
    .heatmap-square.bg-orange-300 {
      background-color: #fb923c;
      color: #7c2d12;
    }
    
    .heatmap-square.bg-orange-400 {
      background-color: #f97316;
      color: white;
    }
    
    .heatmap-square.bg-orange-500 {
      background-color: #ea580c;
      color: white;
    }
    
    .insights-section {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 12px;
      margin-top: 20px;
    }
    
    .insight-card {
      display: flex;
      align-items: center;
      padding: 12px;
      background-color: #f7fafc;
      border-radius: 6px;
      border: 1px solid #e2e8f0;
    }
    
    .insight-icon {
      font-size: 1.2rem;
      margin-right: 12px;
    }
    
    .insight-content h5 {
      font-size: 0.875rem;
      font-weight: 600;
      color: #2d3748;
      margin: 0 0 4px 0;
    }
    
    .insight-content p {
      font-size: 0.75rem;
      color: #718096;
      margin: 0;
    }
  `]
})
export class EngagementHeatmapComponent implements OnInit {
  activeTab: string = 'engagement';
  
  channelPerformance = [
    {
      name: "WhatsApp",
      engagement: "68.5%",
      peak: "Tue at 10 AM",
      bgColor: "bg-green-50",
      textColor: "text-green-700"
    },
    {
      name: "SMS", 
      engagement: "54.2%",
      peak: "Wed at 11 AM",
      bgColor: "bg-blue-50",
      textColor: "text-blue-700"
    }
  ];

  heatmapData = [
    { day: "Sun", values: [12, 28, 45, 38], percentages: ["12%", "28%", "45%", "38%"] },
    { day: "Mon", values: [25, 42, 68, 72], percentages: ["25%", "42%", "68%", "72%"] },
    { day: "Tue", values: [38, 78, 65, 42], percentages: ["38%", "78%", "65%", "42%"] },
    { day: "Wed", values: [22, 58, 85, 68], percentages: ["22%", "58%", "85%", "68%"] },
    { day: "Thu", values: [15, 45, 62, 48], percentages: ["15%", "45%", "62%", "48%"] },
    { day: "Fri", values: [28, 52, 75, 82], percentages: ["28%", "52%", "75%", "82%"] },
    { day: "Sat", values: [18, 32, 48, 35], percentages: ["18%", "32%", "48%", "35%"] }
  ];

  ngOnInit(): void {}

  getHeatmapColor(value: number): string {
    if (value >= 80) return "bg-orange-500";
    if (value >= 60) return "bg-orange-400";
    if (value >= 40) return "bg-orange-300";
    if (value >= 20) return "bg-orange-200";
    return "bg-orange-100";
  }

  getTextColor(value: number): boolean {
    return value >= 60;
  }
}

// client/src/components/dashboard/engagement-heatmap.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Lightbulb, TrendingUp, CalendarX } from "lucide-react";

export default function EngagementHeatmap() {
  const channelPerformance = [
    {
      name: "WhatsApp",
      engagement: "68.5%",
      peak: "Tue at 10 AM",
      bgColor: "bg-green-50",
      borderColor: "border-green-200",
      textColor: "text-green-700"
    },
    {
      name: "SMS", 
      engagement: "54.2%",
      peak: "Wed at 11 AM",
      bgColor: "bg-blue-50",
      borderColor: "border-blue-200", 
      textColor: "text-blue-700"
    }
  ];

  const heatmapData = [
    { day: "Sun", values: [12, 28, 45, 38], percentages: ["12%", "28%", "45%", "38%"] },
    { day: "Mon", values: [25, 42, 68, 72], percentages: ["25%", "42%", "68%", "72%"] },
    { day: "Tue", values: [38, 78, 65, 42], percentages: ["38%", "78%", "65%", "42%"] },
    { day: "Wed", values: [22, 58, 85, 68], percentages: ["22%", "58%", "85%", "68%"] },
    { day: "Thu", values: [15, 45, 62, 48], percentages: ["15%", "45%", "62%", "48%"] },
    { day: "Fri", values: [28, 52, 75, 82], percentages: ["28%", "52%", "75%", "82%"] },
    { day: "Sat", values: [18, 32, 48, 35], percentages: ["18%", "32%", "48%", "35%"] }
  ];

  const getHeatmapColor = (value: number) => {
    if (value >= 80) return "bg-orange-500";
    if (value >= 60) return "bg-orange-400";
    if (value >= 40) return "bg-orange-300";
    if (value >= 20) return "bg-orange-200";
    return "bg-orange-100";
  };

  const getTextColor = (value: number) => {
    return value >= 60 ? "text-white" : "text-gray-800";
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-xl font-semibold text-gray-900">Peak Engagement Heatmap</CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="engagement" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="engagement" data-testid="tab-engagement">Engagement</TabsTrigger>
            <TabsTrigger value="conversion" data-testid="tab-conversion">Conversion</TabsTrigger>
            <TabsTrigger value="cost" data-testid="tab-cost">Cost Efficiency</TabsTrigger>
          </TabsList>
          
          <TabsContent value="engagement" className="space-y-6">
            {/* Top Performing Channels */}
            <div className="grid grid-cols-2 gap-4">
              {channelPerformance.map((channel, index) => (
                <div 
                  key={index}
                  className={`${channel.bgColor} ${channel.borderColor} border rounded-lg p-4`}
                  data-testid={`channel-performance-${index}`}
                >
                  <h3 className="font-medium text-gray-900 mb-2">{channel.name}</h3>
                  <p className={`text-2xl font-bold ${channel.textColor}`}>{channel.engagement}</p>
                  <p className={`text-sm ${channel.textColor} mt-1`}>Peak: {channel.peak}</p>
                </div>
              ))}
            </div>

            {/* Heatmap Grid */}
            <div>
              <h3 className="text-sm font-medium text-gray-900 mb-3">Engagement Heatmap by Time</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr>
                      <th className="text-left py-2 pr-4"></th>
                      <th className="text-center py-2 px-2">12 AM</th>
                      <th className="text-center py-2 px-2">6 AM</th>
                      <th className="text-center py-2 px-2">12 PM</th>
                      <th className="text-center py-2 px-2">6 PM</th>
                    </tr>
                  </thead>
                  <tbody className="space-y-1">
                    {heatmapData.map((row, index) => (
                      <tr key={index}>
                        <td className="text-gray-600 py-2 pr-4">{row.day}</td>
                        {row.values.map((value, cellIndex) => (
                          <td key={cellIndex} className="text-center py-2 px-2">
                            <div 
                              className={`w-8 h-6 ${getHeatmapColor(value)} rounded mx-auto flex items-center justify-center`}
                              data-testid={`heatmap-cell-${index}-${cellIndex}`}
                            >
                              <span className={`text-xs font-medium ${getTextColor(value)}`}>
                                {row.percentages[cellIndex]}
                              </span>
                            </div>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              
              {/* Legend */}
              <div className="flex items-center justify-between mt-4">
                <div className="flex items-center space-x-4">
                  <span className="text-xs text-gray-600">Low</span>
                  <div className="flex space-x-1">
                    {[1, 2, 3, 4, 5].map((value) => (
                      <div 
                        key={value}
                        className={`w-3 h-3 ${getHeatmapColor(value)} rounded`}
                      ></div>
                    ))}
                  </div>
                  <span className="text-xs text-gray-600">High</span>
                </div>
              </div>
            </div>

            {/* Optimal Timing Recommendations */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-center mb-3">
                <Lightbulb className="w-5 h-5 text-blue-600 mr-2" />
                <h3 className="font-medium text-blue-900">Optimal Timing Recommendations</h3>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="flex items-center mb-2">
                    <TrendingUp className="w-4 h-4 text-green-600 mr-2" />
                    <span className="font-medium text-gray-900">Best Times</span>
                  </div>
                  <p className="text-sm text-gray-600">
                    Tuesday-Thursday 10-11 AM show 35% higher engagement
                  </p>
                </div>
                <div>
                  <div className="flex items-center mb-2">
                    <CalendarX className="w-4 h-4 text-orange-600 mr-2" />
                    <span className="font-medium text-gray-900">Avoid Times</span>
                  </div>
                  <p className="text-sm text-gray-600">
                    Late evenings (8-10 PM) show 60% lower conversion rates
                  </p>
                </div>
              </div>
              <Button 
                variant="link" 
                className="text-primary hover:underline p-0 mt-3"
                data-testid="button-schedule-optimally"
              >
                Schedule Campaigns Optimally →
              </Button>
            </div>
          </TabsContent>
          
          <TabsContent value="conversion">
            <div className="text-center py-8 text-gray-500">
              Conversion timing analysis coming soon...
            </div>
          </TabsContent>
          
          <TabsContent value="cost">
            <div className="text-center py-8 text-gray-500">
              Cost efficiency analysis coming soon...
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
