// client/src/app/components/festival-timeline/festival-timeline.component.ts
import { Component, OnInit } from '@angular/core';

interface Holiday {
  name: string;
  date: Date;
  status: string;
  campaigns: number;
  expectedRevenue: string;
  engagement: string;
  color: string;
  category: string;
  description: string;
  preparationDays: number;
  conversionRate: string;
}

@Component({
  selector: 'app-festival-timeline',
  template: `
    <div class="card">
      <div class="card-header">
        <div class="header-content">
          <div class="title-section">
            <div class="icon">🎊</div>
            <div>
              <h3 class="card-title">Festival Performance Timeline</h3>
              <p class="card-subtitle">AI-powered holiday and event campaign planning</p>
            </div>
          </div>
          <div class="controls">
            <select [(ngModel)]="selectedCategory" class="filter-select" (change)="filterHolidays()">
              <option value="all">All Categories</option>
              <option value="Festival">Festivals</option>
              <option value="Religious">Religious</option>
              <option value="Shopping">Shopping</option>
              <option value="Romance">Romance</option>
            </select>
            <button class="ai-btn" (click)="generateAIInsights()">🤖 AI Insights</button>
          </div>
        </div>
      </div>
      
      <div class="card-content">
        <!-- Festival Stats Overview -->
        <div class="festival-stats">
          <div class="stat-item">
            <div class="stat-icon">📅</div>
            <div class="stat-info">
              <h4>{{getUpcomingFestivals()}}</h4>
              <p>Upcoming Festivals</p>
              <span class="stat-detail">Next 90 days</span>
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-icon">💰</div>
            <div class="stat-info">
              <h4>{{getTotalRevenuePotential()}}</h4>
              <p>Revenue Potential</p>
              <span class="stat-detail">Projected earnings</span>
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-icon">🎯</div>
            <div class="stat-info">
              <h4>{{getTotalCampaigns()}}</h4>
              <p>Planned Campaigns</p>
              <span class="stat-detail">Across all festivals</span>
            </div>
          </div>
          <div class="stat-item">
            <div class="stat-icon">📈</div>
            <div class="stat-info">
              <h4>{{getAverageEngagement()}}</h4>
              <p>Avg Engagement Lift</p>
              <span class="stat-detail">During festivals</span>
            </div>
          </div>
        </div>

        <!-- Timeline View -->
        <div class="timeline-section">
          <h4>Festival Timeline & Campaign Schedule</h4>
          <div class="timeline-container">
            <div class="timeline-line"></div>
            <div *ngFor="let holiday of displayedHolidays; let i = index" 
                 class="timeline-item" 
                 [ngClass]="holiday.status"
                 [style.left.px]="getTimelinePosition(holiday.date)">
              
              <div class="timeline-marker" [ngClass]="holiday.color">
                <div class="marker-dot"></div>
              </div>
              
              <div class="timeline-card" [ngClass]="holiday.color">
                <div class="card-header-mini">
                  <h5>{{holiday.name}}</h5>
                  <span class="category-badge" [ngClass]="getCategoryClass(holiday.category)">
                    {{holiday.category}}
                  </span>
                </div>
                
                <div class="card-content-mini">
                  <div class="holiday-date">
                    <span class="date-text">{{formatDate(holiday.date)}}</span>
                    <span class="days-until" *ngIf="getDaysUntil(holiday.date) > 0">
                      {{getDaysUntil(holiday.date)}} days to go
                    </span>
                  </div>
                  
                  <div class="holiday-metrics">
                    <div class="metric-mini">
                      <span class="metric-label">Campaigns</span>
                      <span class="metric-value">{{holiday.campaigns}}</span>
                    </div>
                    <div class="metric-mini">
                      <span class="metric-label">Revenue</span>
                      <span class="metric-value">{{holiday.expectedRevenue}}</span>
                    </div>
                    <div class="metric-mini">
                      <span class="metric-label">Engagement</span>
                      <span class="metric-value">{{holiday.engagement}}</span>
                    </div>
                    <div class="metric-mini">
                      <span class="metric-label">Conv. Rate</span>
                      <span class="metric-value">{{holiday.conversionRate}}</span>
                    </div>
                  </div>
                  
                  <div class="holiday-description">
                    <p>{{holiday.description}}</p>
                  </div>
                  
                  <div class="holiday-actions">
                    <button class="action-btn primary" (click)="viewCampaigns(holiday)">
                      View Campaigns
                    </button>
                    <button class="action-btn secondary" (click)="planCampaign(holiday)">
                      Plan Campaign
                    </button>
                  </div>
                  
                  <div class="preparation-alert" *ngIf="needsPreparation(holiday)">
                    <div class="alert-icon">⚠️</div>
                    <span>Campaign preparation should start in {{getPreparationDays(holiday)}} days</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Festival Performance Insights -->
        <div class="performance-insights">
          <h4>🎯 Festival Campaign Insights</h4>
          <div class="insights-grid">
            <div class="insight-card trend-analysis">
              <div class="insight-header">
                <span class="insight-icon">📊</span>
                <h5>Trend Analysis</h5>
              </div>
              <div class="trend-chart">
                <div class="trend-line">
                  <div *ngFor="let point of getTrendData()" 
                       class="trend-point" 
                       [style.height.%]="point.value"
                       [style.left.%]="point.position">
                  </div>
                </div>
              </div>
              <p>Festival campaigns show 67% higher engagement vs regular campaigns. Peak performance during Diwali and Christmas periods.</p>
            </div>
            
            <div class="insight-card channel-recommendation">
              <div class="insight-header">
                <span class="insight-icon">📱</span>
                <h5>Channel Recommendations</h5>
              </div>
              <div class="channel-breakdown">
                <div class="channel-item">
                  <span class="channel-name">WhatsApp</span>
                  <div class="channel-bar">
                    <div class="bar-fill whatsapp" style="width: 85%"></div>
                  </div>
                  <span class="channel-score">85%</span>
                </div>
                <div class="channel-item">
                  <span class="channel-name">SMS</span>
                  <div class="channel-bar">
                    <div class="bar-fill sms" style="width: 72%"></div>
                  </div>
                  <span class="channel-score">72%</span>
                </div>
                <div class="channel-item">
                  <span class="channel-name">Email</span>
                  <div class="channel-bar">
                    <div class="bar-fill email" style="width: 45%"></div>
                  </div>
                  <span class="channel-score">45%</span>
                </div>
              </div>
              <p>WhatsApp performs 23% better during festivals. Recommend allocating 60% budget to WhatsApp for maximum ROI.</p>
            </div>
            
            <div class="insight-card timing-optimization">
              <div class="insight-header">
                <span class="insight-icon">⏰</span>
                <h5>Optimal Timing</h5>
              </div>
              <div class="timing-heatmap">
                <div class="time-slots">
                  <div *ngFor="let slot of getOptimalTimes()" 
                       class="time-slot" 
                       [ngClass]="slot.intensity">
                    <span class="slot-time">{{slot.time}}</span>
                    <span class="slot-rate">{{slot.rate}}</span>
                  </div>
                </div>
              </div>
              <p>Send festival campaigns at 10 AM for 34% higher open rates. Avoid sending after 8 PM during religious festivals.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
      margin-bottom: 20px;
    }
    
    .card-header {
      padding: 20px;
      border-bottom: 1px solid #e2e8f0;
    }
    
    .header-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 16px;
    }
    
    .title-section {
      display: flex;
      align-items: center;
    }
    
    .icon {
      font-size: 1.25rem;
      margin-right: 12px;
    }
    
    .card-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: #2d3748;
      margin: 0 0 4px 0;
    }
    
    .card-subtitle {
      font-size: 0.875rem;
      color: #718096;
      margin: 0;
    }
    
    .controls {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    
    .filter-select {
      padding: 6px 12px;
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      background: white;
      color: #2d3748;
    }
    
    .ai-btn {
      padding: 6px 12px;
      border: none;
      border-radius: 6px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      cursor: pointer;
      transition: all 0.2s;
      font-weight: 500;
    }
    
    .ai-btn:hover {
      transform: translateY(-1px);
    }
    
    .card-content {
      padding: 20px;
    }
    
    .festival-stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 16px;
      margin-bottom: 32px;
    }
    
    .stat-item {
      display: flex;
      align-items: center;
      padding: 16px;
      background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
      border-radius: 8px;
      border: 1px solid #e2e8f0;
    }
    
    .stat-icon {
      font-size: 1.5rem;
      margin-right: 12px;
    }
    
    .stat-info h4 {
      font-size: 1.25rem;
      font-weight: 700;
      color: #2d3748;
      margin: 0 0 4px 0;
    }
    
    .stat-info p {
      font-size: 0.875rem;
      color: #4a5568;
      margin: 0 0 2px 0;
    }
    
    .stat-detail {
      font-size: 0.75rem;
      color: #718096;
    }
    
    .timeline-section h4 {
      font-size: 1.1rem;
      font-weight: 600;
      color: #2d3748;
      margin-bottom: 20px;
    }
    
    .timeline-container {
      position: relative;
      padding: 20px 0;
      overflow-x: auto;
      min-height: 400px;
    }
    
    .timeline-line {
      position: absolute;
      top: 50%;
      left: 0;
      right: 0;
      height: 2px;
      background: linear-gradient(90deg, #e2e8f0, #cbd5e0, #e2e8f0);
      transform: translateY(-1px);
    }
    
    .timeline-item {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      z-index: 10;
    }
    
    .timeline-marker {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 15;
    }
    
    .marker-dot {
      width: 12px;
      height: 12px;
      border-radius: 50%;
      background: white;
      border: 3px solid;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .timeline-item.active .marker-dot {
      border-color: #f59e0b;
      animation: pulse 2s infinite;
    }
    
    .timeline-item.upcoming .marker-dot {
      border-color: #3b82f6;
    }
    
    .timeline-item.planned .marker-dot {
      border-color: #10b981;
    }
    
    @keyframes pulse {
      0% { box-shadow: 0 0 0 0 rgba(245, 158, 11, 0.4); }
      70% { box-shadow: 0 0 0 10px rgba(245, 158, 11, 0); }
      100% { box-shadow: 0 0 0 0 rgba(245, 158, 11, 0); }
    }
    
    .timeline-card {
      position: absolute;
      top: 20px;
      left: 50%;
      transform: translateX(-50%);
      width: 280px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
      border: 1px solid;
      padding: 16px;
    }
    
    .timeline-card.border-orange-300 {
      border-color: #fed7aa;
    }
    
    .timeline-card.border-green-300 {
      border-color: #bbf7d0;
    }
    
    .timeline-card.border-blue-300 {
      border-color: #bfdbfe;
    }
    
    .timeline-card.border-purple-300 {
      border-color: #d8b4fe;
    }
    
    .timeline-card.border-pink-300 {
      border-color: #f9a8d4;
    }
    
    .timeline-card.border-yellow-300 {
      border-color: #fde047;
    }
    
    .card-header-mini {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
    }
    
    .card-header-mini h5 {
      font-size: 0.875rem;
      font-weight: 600;
      color: #2d3748;
      margin: 0;
    }
    
    .category-badge {
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: 500;
    }
    
    .category-festival {
      background: #fed7aa;
      color: #c2410c;
    }
    
    .category-religious {
      background: #bbf7d0;
      color: #166534;
    }
    
    .category-shopping {
      background: #d8b4fe;
      color: #7c3aed;
    }
    
    .category-romance {
      background: #f9a8d4;
      color: #be185d;
    }
    
    .holiday-date {
      margin-bottom: 12px;
    }
    
    .date-text {
      font-size: 0.875rem;
      font-weight: 600;
      color: #374151;
      display: block;
    }
    
    .days-until {
      font-size: 0.75rem;
      color: #f59e0b;
      font-weight: 500;
    }
    
    .holiday-metrics {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
      margin-bottom: 12px;
    }
    
    .metric-mini {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    
    .metric-label {
      font-size: 0.75rem;
      color: #6b7280;
    }
    
    .metric-value {
      font-size: 0.75rem;
      font-weight: 600;
      color: #374151;
    }
    
    .holiday-description {
      margin-bottom: 12px;
    }
    
    .holiday-description p {
      font-size: 0.75rem;
      color: #6b7280;
      margin: 0;
      line-height: 1.4;
    }
    
    .holiday-actions {
      display: flex;
      gap: 8px;
      margin-bottom: 8px;
    }
    
    .action-btn {
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 500;
      cursor: pointer;
      transition: all 0.2s;
      flex: 1;
    }
    
    .action-btn.primary {
      background: #3b82f6;
      color: white;
      border: none;
    }
    
    .action-btn.secondary {
      background: white;
      color: #374151;
      border: 1px solid #d1d5db;
    }
    
    .action-btn:hover {
      transform: translateY(-1px);
    }
    
    .preparation-alert {
      display: flex;
      align-items: center;
      padding: 6px;
      background: #fef3c7;
      border-radius: 4px;
      font-size: 0.75rem;
      color: #92400e;
    }
    
    .alert-icon {
      margin-right: 6px;
    }
    
    .performance-insights {
      margin-top: 32px;
      padding-top: 24px;
      border-top: 1px solid #e2e8f0;
    }
    
    .performance-insights h4 {
      font-size: 1.1rem;
      font-weight: 600;
      color: #2d3748;
      margin-bottom: 16px;
    }
    
    .insights-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 20px;
    }
    
    .insight-card {
      padding: 16px;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
    }
    
    .insight-header {
      display: flex;
      align-items: center;
      margin-bottom: 12px;
    }
    
    .insight-icon {
      font-size: 1.1rem;
      margin-right: 8px;
    }
    
    .insight-header h5 {
      font-size: 0.875rem;
      font-weight: 600;
      color: #2d3748;
      margin: 0;
    }
    
    .insight-card p {
      font-size: 0.875rem;
      color: #4a5568;
      margin: 8px 0 0 0;
      line-height: 1.4;
    }
    
    .trend-chart {
      height: 60px;
      background: #f9fafb;
      border-radius: 4px;
      position: relative;
      margin-bottom: 8px;
    }
    
    .trend-line {
      position: relative;
      height: 100%;
    }
    
    .trend-point {
      position: absolute;
      bottom: 0;
      width: 4px;
      background: linear-gradient(180deg, #3b82f6, #1e40af);
      border-radius: 2px;
    }
    
    .channel-breakdown {
      margin-bottom: 8px;
    }
    
    .channel-item {
      display: flex;
      align-items: center;
      margin-bottom: 6px;
      gap: 8px;
    }
    
    .channel-name {
      font-size: 0.75rem;
      font-weight: 500;
      width: 60px;
    }
    
    .channel-bar {
      flex: 1;
      height: 6px;
      background: #e5e7eb;
      border-radius: 3px;
      overflow: hidden;
    }
    
    .bar-fill {
      height: 100%;
      border-radius: 3px;
    }
    
    .bar-fill.whatsapp { background: #10b981; }
    .bar-fill.sms { background: #3b82f6; }
    .bar-fill.email { background: #8b5cf6; }
    
    .channel-score {
      font-size: 0.75rem;
      font-weight: 600;
      width: 30px;
      text-align: right;
    }
    
    .time-slots {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 4px;
      margin-bottom: 8px;
    }
    
    .time-slot {
      padding: 6px;
      border-radius: 4px;
      text-align: center;
      display: flex;
      flex-direction: column;
    }
    
    .time-slot.high {
      background: #dcfce7;
      color: #166534;
    }
    
    .time-slot.medium {
      background: #fef3c7;
      color: #92400e;
    }
    
    .time-slot.low {
      background: #fee2e2;
      color: #991b1b;
    }
    
    .slot-time {
      font-size: 0.75rem;
      font-weight: 600;
    }
    
    .slot-rate {
      font-size: 0.625rem;
    }
  `]
})
export class FestivalTimelineComponent implements OnInit {
  selectedCategory: string = 'all';
  
  holidays: Holiday[] = [
    {
      name: "Diwali",
      date: new Date(2024, 10, 12),
      status: "upcoming",
      campaigns: 3,
      expectedRevenue: "₹12L",
      engagement: "+67%",
      color: "border-orange-300",
      category: "Festival",
      description: "Festival of Lights - Major Indian celebration",
      preparationDays: 7,
      conversionRate: "28%"
    },
    {
      name: "Christmas",
      date: new Date(2024, 11, 25),
      status: "planned",
      campaigns: 5,
      expectedRevenue: "₹25L",
      engagement: "+89%",
      color: "border-green-300",
      category: "Religious",
      description: "Christmas Day - Global Christian holiday",
      preparationDays: 14,
      conversionRate: "35%"
    },
    {
      name: "New Year",
      date: new Date(2025, 0, 1),
      status: "planned",
      campaigns: 2,
      expectedRevenue: "₹8L",
      engagement: "+45%",
      color: "border-blue-300",
      category: "Celebration",
      description: "New Year's Day - Global celebration",
      preparationDays: 10,
      conversionRate: "22%"
    },
    {
      name: "Black Friday",
      date: new Date(2024, 10, 29),
      status: "active",
      campaigns: 8,
      expectedRevenue: "₹45L",
      engagement: "+156%",
      color: "border-purple-300",
      category: "Shopping",
      description: "Black Friday Sale - Major shopping event",
      preparationDays: 3,
      conversionRate: "42%"
    },
    {
      name: "Valentine's Day",
      date: new Date(2025, 1, 14),
      status: "planned",
      campaigns: 4,
      expectedRevenue: "₹15L",
      engagement: "+78%",
      color: "border-pink-300",
      category: "Romance",
      description: "Valentine's Day - Romance and gifts",
      preparationDays: 10,
      conversionRate: "31%"
    },
    {
      name: "Holi",
      date: new Date(2025, 2, 13),
      status: "planned",
      campaigns: 3,
      expectedRevenue: "₹9L",
      engagement: "+56%",
      color: "border-yellow-300",
      category: "Festival",
      description: "Festival of Colors - Indian spring festival",
      preparationDays: 7,
      conversionRate: "25%"
    }
  ];
  
  displayedHolidays: Holiday[] = [];

  ngOnInit(): void {
    this.holidays.sort((a, b) => a.date.getTime() - b.date.getTime());
    this.filterHolidays();
  }

  filterHolidays(): void {
    this.displayedHolidays = this.selectedCategory === 'all' 
      ? this.holidays 
      : this.holidays.filter(h => h.category === this.selectedCategory);
  }

  generateAIInsights(): void {
    console.log('Generating AI insights for festivals...');
  }

  getUpcomingFestivals(): number {
    const now = new Date();
    const future = new Date();
    future.setDate(now.getDate() + 90);
    return this.holidays.filter(h => h.date >= now && h.date <= future).length;
  }

  getTotalRevenuePotential(): string {
    return "₹114L";
  }

  getTotalCampaigns(): number {
    return this.holidays.reduce((total, h) => total + h.campaigns, 0);
  }

  getAverageEngagement(): string {
    return "+69%";
  }

  getTimelinePosition(date: Date): number {
    // Calculate position based on date for timeline
    const now = new Date();
    const daysDiff = Math.floor((date.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    return Math.max(50, Math.min(800, 200 + (daysDiff * 3)));
  }

  formatDate(date: Date): string {
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric',
      year: 'numeric'
    });
  }

  getDaysUntil(date: Date): number {
    const now = new Date();
    return Math.max(0, Math.floor((date.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
  }

  getCategoryClass(category: string): string {
    const classes: {[key: string]: string} = {
      'Festival': 'category-festival',
      'Religious': 'category-religious',
      'Shopping': 'category-shopping',
      'Romance': 'category-romance'
    };
    return classes[category] || 'category-festival';
  }

  needsPreparation(holiday: Holiday): boolean {
    const daysUntil = this.getDaysUntil(holiday.date);
    return daysUntil > 0 && daysUntil <= holiday.preparationDays + 3;
  }

  getPreparationDays(holiday: Holiday): number {
    const daysUntil = this.getDaysUntil(holiday.date);
    return Math.max(0, daysUntil - holiday.preparationDays);
  }

  viewCampaigns(holiday: Holiday): void {
    console.log('Viewing campaigns for:', holiday.name);
  }

  planCampaign(holiday: Holiday): void {
    console.log('Planning campaign for:', holiday.name);
  }

  getTrendData() {
    return [
      { value: 30, position: 10 },
      { value: 45, position: 25 },
      { value: 80, position: 40 },
      { value: 65, position: 55 },
      { value: 90, position: 70 },
      { value: 75, position: 85 }
    ];
  }

  getOptimalTimes() {
    return [
      { time: '10 AM', rate: '34%', intensity: 'high' },
      { time: '2 PM', rate: '28%', intensity: 'medium' },
      { time: '6 PM', rate: '31%', intensity: 'high' },
      { time: '8 PM', rate: '18%', intensity: 'low' }
    ];
  }
}

// client/src/components/dashboard/festival-timeline.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CalendarDays, TrendingUp, Target, Users, Clock, Plus, Calendar, Lightbulb } from "lucide-react";
import { useState, useEffect } from "react";

export default function FestivalTimeline() {
  const [holidays, setHolidays] = useState([]);
  const [loading, setLoading] = useState(true);

  // Auto-detect holidays using date calculations
  useEffect(() => {
    const detectHolidays = () => {
      const currentYear = new Date().getFullYear();
      const detectedHolidays = [
        {
          name: "Diwali",
          date: new Date(currentYear, 10, 12), // November 12 (estimated)
          status: "upcoming",
          campaigns: 3,
          expectedRevenue: "₹12L",
          engagement: "+67%",
          color: "border-orange-300 bg-orange-50",
          category: "Festival",
          description: "Festival of Lights - Major Indian celebration",
          preparationDays: 7,
          conversionRate: "28%"
        },
        {
          name: "Christmas",
          date: new Date(currentYear, 11, 25), // December 25
          status: "planned",
          campaigns: 5,
          expectedRevenue: "₹25L",
          engagement: "+89%",
          color: "border-green-300 bg-green-50",
          category: "Religious",
          description: "Christmas Day - Global Christian holiday",
          preparationDays: 14,
          conversionRate: "35%"
        },
        {
          name: "New Year",
          date: new Date(currentYear + 1, 0, 1), // January 1 next year
          status: "planned",
          campaigns: 2,
          expectedRevenue: "₹8L",
          engagement: "+45%",
          color: "border-blue-300 bg-blue-50",
          category: "Celebration",
          description: "New Year's Day - Global celebration",
          preparationDays: 10,
          conversionRate: "22%"
        },
        {
          name: "Black Friday",
          date: new Date(currentYear, 10, 29), // November 29 (4th Friday of November)
          status: "active",
          campaigns: 8,
          expectedRevenue: "₹45L",
          engagement: "+156%",
          color: "border-purple-300 bg-purple-50",
          category: "Shopping",
          description: "Black Friday Sale - Major shopping event",
          preparationDays: 3,
          conversionRate: "42%"
        },
        {
          name: "Valentine's Day",
          date: new Date(currentYear + 1, 1, 14), // February 14 next year
          status: "planned",
          campaigns: 4,
          expectedRevenue: "₹15L",
          engagement: "+78%",
          color: "border-pink-300 bg-pink-50",
          category: "Romance",
          description: "Valentine's Day - Romance and gifts",
          preparationDays: 10,
          conversionRate: "31%"
        },
        {
          name: "Holi",
          date: new Date(currentYear + 1, 2, 13), // March 13 next year (estimated)
          status: "planned",
          campaigns: 3,
          expectedRevenue: "₹9L",
          engagement: "+56%",
          color: "border-yellow-300 bg-yellow-50",
          category: "Festival",
          description: "Festival of Colors - Indian spring festival",
          preparationDays: 7,
          conversionRate: "25%"
        }
      ];

      // Sort by date
      detectedHolidays.sort((a, b) => a.date.getTime() - b.date.getTime());
      
      setHolidays(detectedHolidays);
      setLoading(false);
    };

    detectHolidays();
  }, []);

  const formatDate = (date) => {
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getDaysUntil = (date) => {
    const today = new Date();
    const diffTime = date.getTime() - today.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays;
  };

  const getStatusBadge = (status, daysUntil) => {
    if (daysUntil < 0) return { text: "Completed", class: "bg-gray-100 text-gray-800" };
    if (daysUntil <= 7) return { text: "Active", class: "bg-green-100 text-green-800" };
    if (daysUntil <= 30) return { text: "Upcoming", class: "bg-orange-100 text-orange-800" };
    return { text: "Planned", class: "bg-blue-100 text-blue-800" };
  };

  const campaignInsights = [
    {
      insight: "Black Friday campaigns show 3x higher conversion rates",
      action: "Increase budget allocation by 40%",
      impact: "+₹18L potential revenue"
    },
    {
      insight: "Christmas campaigns perform best with 14-day lead time",
      action: "Start campaigns December 11th",
      impact: "35% better engagement"
    },
    {
      insight: "Festival campaigns need regional customization",
      action: "Create region-specific content",
      impact: "67% higher local engagement"
    }
  ];

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <Calendar className="w-5 h-5 text-purple-600 mr-2" />
            <div>
              <CardTitle className="text-xl font-semibold text-gray-900">Festival Performance Timeline</CardTitle>
              <p className="text-sm text-gray-600 mt-1">Auto-detected holidays & campaign planning inspired by Salesforce Marketing Cloud</p>
            </div>
          </div>
          <Button variant="outline" size="sm" data-testid="button-add-holiday">
            <Plus className="w-4 h-4 mr-2" />
            Add Custom Holiday
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="text-center py-8">
            <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto"></div>
            <p className="text-sm text-gray-600 mt-2">Detecting holidays...</p>
          </div>
        ) : (
          <>
            {/* Holiday Timeline Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              {holidays.slice(0, 6).map((holiday, index) => {
                const daysUntil = getDaysUntil(holiday.date);
                const statusBadge = getStatusBadge(holiday.status, daysUntil);
                
                return (
                  <div 
                    key={index}
                    className={`${holiday.color} border rounded-lg p-4 hover:shadow-md transition-shadow`}
                    data-testid={`holiday-card-${index}`}
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div>
                        <h3 className="font-medium text-gray-900">{holiday.name}</h3>
                        <p className="text-sm text-gray-600">{formatDate(holiday.date)}</p>
                      </div>
                      <Badge className={statusBadge.class}>{statusBadge.text}</Badge>
                    </div>
                    
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Category</span>
                        <span className="font-medium">{holiday.category}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Campaigns</span>
                        <span className="font-medium">{holiday.campaigns}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Expected Revenue</span>
                        <span className="font-medium text-green-600">{holiday.expectedRevenue}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Conversion Rate</span>
                        <span className="font-medium text-blue-600">{holiday.conversionRate}</span>
                      </div>
                    </div>
                    
                    <div className="mt-3 pt-3 border-t border-gray-200">
                      <div className="flex items-center justify-between">
                        <div className="text-xs text-gray-600">
                          {daysUntil > 0 ? (
                            <span className="flex items-center">
                              <Clock className="w-3 h-3 mr-1" />
                              {daysUntil} days to go
                            </span>
                          ) : daysUntil === 0 ? (
                            <span className="text-green-600 font-medium">Today!</span>
                          ) : (
                            <span>Completed</span>
                          )}
                        </div>
                        <Button 
                          variant="link" 
                          size="sm" 
                          className="text-primary hover:underline p-0 h-auto text-xs"
                          data-testid={`button-plan-campaign-${index}`}
                        >
                          {daysUntil > 0 ? "Plan Campaign" : "View Results"}
                        </Button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Campaign Planning Insights */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Timeline Optimization */}
              <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                <div className="flex items-center mb-3">
                  <Lightbulb className="w-5 h-5 text-purple-600 mr-2" />
                  <h3 className="font-medium text-purple-900">Campaign Planning Insights</h3>
                </div>
                <div className="space-y-3">
                  {campaignInsights.map((insight, index) => (
                    <div key={index} className="bg-white border border-purple-200 rounded-lg p-3">
                      <p className="text-sm text-gray-900 font-medium mb-1">{insight.insight}</p>
                      <p className="text-xs text-gray-600 mb-2">{insight.action}</p>
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-green-600 font-medium">{insight.impact}</span>
                        <Button 
                          size="sm" 
                          variant="outline"
                          className="text-xs"
                          data-testid={`button-apply-insight-${index}`}
                        >
                          Apply
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Upcoming Holiday Alerts */}
              <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
                <div className="flex items-center mb-3">
                  <CalendarDays className="w-5 h-5 text-orange-600 mr-2" />
                  <h3 className="font-medium text-orange-900">Upcoming Campaign Deadlines</h3>
                </div>
                <div className="space-y-3">
                  {holidays.filter(h => getDaysUntil(h.date) > 0 && getDaysUntil(h.date) <= 30).map((holiday, index) => {
                    const daysUntil = getDaysUntil(holiday.date);
                    const preparationDeadline = daysUntil - holiday.preparationDays;
                    
                    return (
                      <div key={index} className="bg-white border border-orange-200 rounded-lg p-3">
                        <div className="flex items-center justify-between mb-2">
                          <div>
                            <p className="font-medium text-gray-900">{holiday.name}</p>
                            <p className="text-xs text-gray-600">{formatDate(holiday.date)}</p>
                          </div>
                          <Badge className={preparationDeadline <= 0 ? "bg-red-100 text-red-800" : "bg-yellow-100 text-yellow-800"}>
                            {preparationDeadline <= 0 ? "Urgent" : `${preparationDeadline}d prep`}
                          </Badge>
                        </div>
                        <div className="text-xs text-gray-600">
                          <p>Campaign prep needed: {holiday.preparationDays} days before</p>
                          <p>Expected engagement: {holiday.engagement}</p>
                        </div>
                        <Button 
                          size="sm" 
                          className={`w-full mt-2 text-xs ${preparationDeadline <= 0 ? 'bg-red-600 hover:bg-red-700' : 'bg-orange-600 hover:bg-orange-700'} text-white`}
                          data-testid={`button-start-campaign-${index}`}
                        >
                          {preparationDeadline <= 0 ? "Start Campaign Now" : "Schedule Campaign"}
                        </Button>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Performance Summary */}
            <div className="mt-6 bg-gray-50 border border-gray-200 rounded-lg p-4">
              <h3 className="font-medium text-gray-900 mb-3">Festival Campaign Performance Summary</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="text-center">
                  <p className="text-2xl font-bold text-blue-600">₹89L</p>
                  <p className="text-sm text-gray-600">Total Festival Revenue</p>
                </div>
                <div className="text-center">
                  <p className="text-2xl font-bold text-green-600">32%</p>
                  <p className="text-sm text-gray-600">Avg Conversion Rate</p>
                </div>
                <div className="text-center">
                  <p className="text-2xl font-bold text-purple-600">6.8x</p>
                  <p className="text-sm text-gray-600">Festival ROI</p>
                </div>
                <div className="text-center">
                  <p className="text-2xl font-bold text-orange-600">25</p>
                  <p className="text-sm text-gray-600">Active Campaigns</p>
                </div>
              </div>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
